# Generated by Django 3.1.4 on 2021-01-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20210104_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='question_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='question_count_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='status_detail_text',
            field=models.CharField(default='INITIAL', max_length=160),
        ),
        migrations.AddField(
            model_name='quiz',
            name='status_text',
            field=models.CharField(default='INITIAL', max_length=80),
        ),
    ]
