# Generated by Django 3.1.4 on 2021-01-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20210123_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='first_question_id',
            field=models.IntegerField(default=0),
        ),
    ]
