# Generated by Django 3.1.4 on 2022-12-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_quiz_first_question_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='author',
            field=models.CharField(default='unknown', max_length=80),
        ),
    ]
